name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
      continue-on-error: true
    
    - name: Build
      run: npm run build
    
    - name: Test
      run: npm test
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
        flags: unittests
        fail_ci_if_error: false
      # Only run this step if the CODECOV_TOKEN secret is available
      if: github.repository == 'copyleftdev/api-metering-libary' && github.event_name != 'pull_request'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
